# _config.yml
title: Samuel Nkrumah # Your Name
description: "Healthcare Data Specialist | Physician Assitant | Data Storyteller" # Your Tagline
baseurl: "" # Leave this blank for a USERNAME.github.io repo
url: "https://sammyorbz.github.io" # Replace with your actual GitHub username

# The most important part: Choose a theme.
# We'll use a popular, professional one for this example.
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme # This tells Jekyll to use the remote theme

# Your social links (edit these)
github_username:  sammyorbz # Your GitHub handle without the @
# You can add others like linkedin, twitter later.
